version: '3.8'

volumes:
  starter-cake-mysql:
    driver: local
  starter-cake-mariadb:
    driver: local

networks:
  starter-cake-net:
    driver: bridge

services:
  app:
    build: .
    container_name: cake-app
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    ports:
      - ${APP_PORT:-80}:80
    networks:
      - starter-cake-net
    depends_on:
      - mysql

  # mysql:
  #   image: mysql
  #   restart: always
  #   ports:
  #     - '${DB_PORT:-3306}:3306'
  #   environment:
  #     MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
  #     MYSQL_ROOT_HOST: '%'
  #     MYSQL_DATABASE: '${DB_DATABASE}'
  #     MYSQL_USER: '${DB_USERNAME}'
  #     MYSQL_PASSWORD: '${DB_PASSWORD}'
  #   volumes:
  #     - 'starter-cake-mysql:/var/lib/mysql'
  #   networks:
  #     - starter-cake-net
  #   healthcheck:
  #     test:
  #       - CMD
  #       - mysqladmin
  #       - ping
  #       - '-p${DB_PASSWORD}'
  #     retries: 3
  #     timeout: 5s
  mysql:
   image: mariadb:10.2
   restart: always
   ports:
     - '${DB_PORT:-3306}:3306'
   environment:
     MARIADB_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
     MARIADB_ROOT_HOST: '%'
     MARIADB_DATABASE: '${DB_DATABASE}'
     MARIADB_USER: '${DB_USERNAME}'
     MARIADB_PASSWORD: '${DB_PASSWORD}'
   volumes:
     - 'starter-cake-mariadb:/var/lib/mysql'
   networks:
     - starter-cake-net

  phpmyadmin:
    image: phpmyadmin
    restart: always
    networks:
      - starter-cake-net
    ports:
      - ${PHPMYADMIN_PORT:-8080}:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${PHPMYADMIN_DB_HOST:-mysql}
      - PMA_PORTS=${PHPMYADMIN_DB_PORT:-3306}
